apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: saytruth-dev
  labels:
    app: kong
spec:
  type: LoadBalancer
  selector:
    app: kong
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: saytruth-prod
  labels:
    app: kong
spec:
  type: LoadBalancer
  selector:
    app: kong
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
