apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: NodePort   # يمكن الوصول من خارج الكلاستر
  selector:
    app: kong
  ports:
    - name: proxy-http
      port: 8000        # داخل الكلاستر
      targetPort: 8000  # داخل الـ Pod
      nodePort: 30080   # للوصول من خارج الكلاستر
    - name: proxy-https
      port: 8443
      targetPort: 8443
      nodePort: 30443
    - name: admin-http
      port: 8001
      targetPort: 8001
    - name: admin-https
      port: 8444
      targetPort: 8444
