apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: saytruth-dev
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: saytruth-prod
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
